[package]
name = "gst-flvsubmux"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["Elliott Linder <elliott@linder.dev>"]
license = "MPL-2.0"
description = "GStreamer element that strictly aggregates timed text into a muxed FLV stream"
repository = "https://github.com/darfink/gst-plugins-darfink"

[dependencies]
gst = { package = "gstreamer", version = "0.25", features = ["v1_20"] }
gst_base = { package = "gstreamer-base", version = "0.25", features = ["v1_20"] }

[dev-dependencies]
gst-check = { package = "gstreamer-check", version = "0.25" }
gst_app = { version = "0.25", package = "gstreamer-app" }

[lib]
name = "gstflvsubmux"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
static = []
capi = []
doc = ["gst/v1_18"]

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gobject-2.0, glib-2.0, gmodule-2.0"
